-- Add new MetricType enum values for e-commerce metrics
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'FATURAMENTO';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'TICKET_MEDIO';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'TAXA_CONVERSAO';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'CPS';
ALTER TYPE "MetricType" ADD VALUE IF NOT EXISTS 'CPM';
